gems:

repositories:
  remote:
    - https://repo1.maven.org/maven2

artifacts:
  simple_common: org.simpleframework:simple-common:jar:6.0.1
  simple_transport: org.simpleframework:simple-transport:jar:6.0.1
  simple_http: org.simpleframework:simple-http:jar:6.0.1
  undertow: io.undertow:undertow-core:jar:2.2.2.Final
  mustache: com.samskivert:jmustache:jar:1.15

  # -- testing dependencies
  hamcrest: org.hamcrest:hamcrest:jar:2.2
  juniversalchardet: com.googlecode.juniversalchardet:juniversalchardet:jar:1.0.3

  # -- test dependencies
  jmock: org.jmock:jmock:jar:2.12.0
  jmock_junit: org.jmock:jmock-junit4:jar:2.12.0

jmock: 2.12.0
junit: 4.13.1